version: "3"

networks:
    keycloak-net:
        driver: bridge

services:
    #######################################
    # Keycloak database
    #######################################
    keycloak-db:
        container_name: "keycloak-db"
        image: postgres:9.6
        volumes:
            - ../volumes/keycloack/data:/var/lib/postgresql/data
        ports:
            - "25432:5432"
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password
        networks:
            - keycloak-net

    #######################################
    # Keycloak auth server
    #######################################
    keycloak:
        container_name: "keycloak"
        image: jboss/keycloak:latest
        depends_on:
            - keycloak-db
        links:
            - keycloak-db
        ports:
            - "8180:8080"
        environment:
            #            PROXY_ADDRESS_FORWARDING: "true"
            DB_VENDOR: POSTGRES
            DB_ADDR: keycloak-db
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_PASSWORD: password
            DB_PORT: 5432
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
        networks:
            - keycloak-net