version: '3'
services:
    db_auth:
        container_name: db_auth
        image: mariadb:latest
        restart: always
        ports:
            - "3307:3306"
        environment:
            MARIADB_USER: auth
            MARIADB_PASSWORD: auth123
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: auth_service
            MARIADB_PORT_NUMBER: 3307
        volumes:
            - './volumes/database/auth/mysql:/var/lib/mysql'
        networks:
            - ${GLOBAL_NETWORK}

    db_issues:
        container_name: db_issues
        image: mariadb:latest
        restart: always
        ports:
            - "3310:3306"
        environment:
            MARIADB_USER: auth
            MARIADB_PASSWORD: auth123
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: issues_service
            MARIADB_PORT_NUMBER: 3310
        volumes:
            - './volumes/database/issues/mysql:/var/lib/mysql'
        networks:
            - ${GLOBAL_NETWORK}

    db_member:
        container_name: db_member
        image: mariadb:latest
        restart: always
        ports:
            - "3311:3306"
        environment:
            MARIADB_USER: auth
            MARIADB_PASSWORD: auth123
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: members_service
            MARIADB_PORT_NUMBER: 3311
        volumes:
            - './volumes/database/member/mysql:/var/lib/mysql'
        networks:
            - ${GLOBAL_NETWORK}

    db_organization:
        container_name: db_organization
        image: mariadb:latest
        restart: always
        ports:
            - "3312:3306"
        environment:
            MARIADB_USER: auth
            MARIADB_PASSWORD: auth123
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: organization_service
            MARIADB_PORT_NUMBER: 3312
        volumes:
            - './volumes/database/organization/mysql:/var/lib/mysql'
        networks:
            - ${GLOBAL_NETWORK}

    organization-service:
        container_name: organization-service
        image: organization-service:latest
#        restart: always
        build:
            context: ../../organization-service/
        ports:
            - "8186:8186"
        environment:
            DATABASE_HOST: db_organization
            MARIADB_PORT_NUMBER: 3312
        links:
            - db_organization
        depends_on:
            -   db_organization
        networks:
            - ${GLOBAL_NETWORK}
#volumes:
#    database/auth/mysql:
#        driver: local
#    database/attachments/mysql:
#        driver: local
#    database/comment/mysql:
#        driver: local
#    database/issues/mysql:
#        driver: local
#    database/member/mysql:
#        driver: local
#    database/organization/mysql:
#        driver: local
#    database/project/mysql:
#        driver: local