version: '3'
services:
    db_auth:
        container_name: pds_auth_db
        image: mariadb:latest
        restart: always
        ports:
            - "3307:3306"
        environment:
            MARIADB_USER: auth
            MARIADB_PASSWORD: auth123
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: auth_service
            MARIADB_PORT_NUMBER: 3307
        volumes:
            - './volumes/database/auth/mysql:/var/lib/mysql'
        networks:
            - ${GLOBAL_NETWORK:-kafka}

    db_attachments:
        container_name: pds_attachments_db
        image: mariadb:latest
        restart: always
        ports:
            - "3308:3306"
        environment:
            MARIADB_USER: auth
            MARIADB_PASSWORD: auth123
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: attachments_service
            MARIADB_PORT_NUMBER: 3308
        volumes:
            - './volumes/database/attachments/mysql:/var/lib/mysql'
        networks:
            - ${GLOBAL_NETWORK:-kafka}

    db_comments:
        container_name: pds_comments_db
        image: mariadb:latest
        restart: always
        ports:
            - "3309:3306"
        environment:
            MARIADB_USER: auth
            MARIADB_PASSWORD: auth123
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: comments_service
            MARIADB_PORT_NUMBER: 3309
        volumes:
            - './volumes/database/comment/mysql:/var/lib/mysql'
        networks:
            - ${GLOBAL_NETWORK:-kafka}

    db_issues:
        container_name: pds_issues_db
        image: mariadb:latest
        restart: always
        ports:
            - "3310:3306"
        environment:
            MARIADB_USER: auth
            MARIADB_PASSWORD: auth123
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: issues_service
            MARIADB_PORT_NUMBER: 3310
        volumes:
            - './volumes/database/issues/mysql:/var/lib/mysql'
        networks:
            - ${GLOBAL_NETWORK:-kafka}

    db_member:
        container_name: pds_member_db
        image: mariadb:latest
        restart: always
        ports:
            - "3311:3306"
        environment:
            MARIADB_USER: auth
            MARIADB_PASSWORD: auth123
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: members_service
            MARIADB_PORT_NUMBER: 3311
        volumes:
            - './volumes/database/member/mysql:/var/lib/mysql'
        networks:
            - ${GLOBAL_NETWORK:-kafka}

    db_organization:
        container_name: pds_organization_db
        image: mariadb:latest
        restart: always
        ports:
            - "3312:3306"
        environment:
            MARIADB_USER: auth
            MARIADB_PASSWORD: auth123
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: organization_service
            MARIADB_PORT_NUMBER: 3312
        volumes:
            - './volumes/database/organization/mysql:/var/lib/mysql'
        networks:
            - ${GLOBAL_NETWORK:-kafka}

    db_project:
        container_name: pds_project_db
        image: mariadb:latest
        restart: always
        ports:
            - "3313:3306"
        environment:
            MARIADB_USER: auth
            MARIADB_PASSWORD: auth123
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: project_service
            MARIADB_PORT_NUMBER: 3313
        volumes:
            - './volumes/database/project/mysql:/var/lib/mysql'
        networks:
            - ${GLOBAL_NETWORK:-kafka}

#volumes:
#    database/auth/mysql:
#        driver: local
#    database/attachments/mysql:
#        driver: local
#    database/comment/mysql:
#        driver: local
#    database/issues/mysql:
#        driver: local
#    database/member/mysql:
#        driver: local
#    database/organization/mysql:
#        driver: local
#    database/project/mysql:
#        driver: local