version: '3'
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:${KAFKA_VERSION:-latest}
        hostname: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_INIT_LIMIT: 5
            ZOOKEEPER_SYNC_LIMIT: 2
            ZOOKEEPER_SERVERS: zookeeper:2888:3888
#            KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=ruok"
            KAFKA_JMX_OPTS: "-Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false"
            KAFKA_JMX_PORT: 49999
        volumes:
            - "./volumes/zookeeper/data:/var/lib/zookeeper/data"
            - "./volumes/zookeeper/transactions:/var/lib/zookeeper/log"
        networks:
            - ${GLOBAL_NETWORK}

    kafka-broker-1:
        image: confluentinc/cp-kafka:${KAFKA_VERSION}
        hostname: kafka-broker-1
        container_name: kafka-broker-1
        ports:
            - "19092:19092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-1:9092,LISTENER_LOCAL://localhost:19092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
#            KAFKA_COMPRESSION_TYPE: producer
        volumes:
            - "./volumes/kafka/broker-1:/var/lib/kafka/data"
        networks:
            - ${GLOBAL_NETWORK}
        depends_on:
            -   zookeeper

    kafka-broker-2:
        image: confluentinc/cp-kafka:${KAFKA_VERSION}
        hostname: kafka-broker-2
        container_name: kafka-broker-2
        ports:
            - "29092:29092"
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-2:9092,LISTENER_LOCAL://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
#            KAFKA_COMPRESSION_TYPE: producer
        volumes:
            - "./volumes/kafka/broker-2:/var/lib/kafka/data"
        networks:
            - ${GLOBAL_NETWORK}
        depends_on:
            - zookeeper

    kafka-broker-3:
        image: confluentinc/cp-kafka:${KAFKA_VERSION}
        hostname: kafka-broker-3
        container_name: kafka-broker-3
        ports:
            - "39092:39092"
        environment:
            KAFKA_BROKER_ID: 3
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-3:9092,LISTENER_LOCAL://localhost:39092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
#            KAFKA_COMPRESSION_TYPE: producer
        volumes:
            - "./volumes/kafka/broker-3:/var/lib/kafka/data"
        networks:
            - ${GLOBAL_NETWORK}
        depends_on:
            -   zookeeper

    kafka-manager:
        image: hlebalbau/kafka-manager:stable
        restart: always
        ports:
            - "9000:9000"
        environment:
            ZK_HOSTS: "zookeeper:2181"
        networks:
            - ${GLOBAL_NETWORK}
        depends_on:
            - zookeeper
