version: '3'
services:
    organization-service:
        hostname: organization-service
        container_name: organization-service
        image: vanket/organization-service:v1.0.0
        restart: always
        ports:
            - "8186:8186"
        environment:
            DATABASE_HOST: db_organization
            MARIADB_PORT_NUMBER: 3306
            LOGSTASH_HOST_PORT: logstash:5000
            KAFKA_HOST: 146.190.105.184
        networks:
            - ${GLOBAL_NETWORK}

    user-service:
        hostname: user-service
        container_name: user-service
        image: vanket/user-service:v1.0.0
        restart: always
        ports:
            - "8182:8182"
        environment:
            DATABASE_HOST: db_auth
            MARIADB_PORT_NUMBER: 3306
            REDIS_HOST: redis_auth
            REDIS_PORT: 6379
            LOGSTASH_HOST_PORT: logstash:5000
            ORGANIZATION_HOST: organization-service
            KAFKA_HOST: 146.190.105.184
        networks:
            - ${GLOBAL_NETWORK}

    member-service:
        hostname: member-service
        container_name: member-service
        image: vanket/member-service:v1.0.0
        restart: always
        ports:
            - "8185:8185"
        environment:
            DATABASE_HOST: db_member
            MARIADB_PORT_NUMBER: 3306
            LOGSTASH_HOST_PORT: logstash:5000
            KAFKA_HOST: 146.190.105.184
        networks:
            - ${GLOBAL_NETWORK}

    issues-service:
        hostname: issues-service
        container_name: issues-service
        image: vanket/issues-service:v1.0.0
        restart: always
        ports:
            - "8184:8184"
        environment:
            DATABASE_HOST: db_issues
            MARIADB_PORT_NUMBER: 3306
            LOGSTASH_HOST_PORT: logstash:5000
        networks:
            - ${GLOBAL_NETWORK}

