server:
    port: 8185

spring:
    profiles:
        active: dev
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB

# Config Swagger  UI
springdoc:
    api-docs:
        path: /v1/api-docs
    swagger-ui:
        path: /swagger-ui-custom.html
        operationsSorter: method