spring:
    datasource:
        url: jdbc:mariadb://${DATABASE_HOST:139.59.96.208}:${MARIADB_PORT_NUMBER:3310}/issues_service?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: auth
        password: auth123
        driver-class-name: org.mariadb.jdbc.Driver
        hikari:
            maximum-pool-size: 10
            max-lifetime: 1800000
            idle-timeout: 600000
            connection-timeout: 30000
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDB103Dialect
    cache:
        type: redis
        redis:
            cache-null-values: false
            use-key-prefix: true
    redis:
        database: 1
        host: ${REDIS_HOST:139.59.96.208}
        port: 6379
        timeout: 10000ms
        lettuce:
            pool:
                max-active: 8
                max-wait: -1ms
                max-idle: 8
                min-idle: 8
#    zipkin:
#        base-url: http://146.190.105.184:9411
#        sender:
#            type: web
#        service:
#            name: issues-service
#    sleuth:
#        sampler:
#            probability: 1.0

management:
    health:
        circuitbreakers:
            enabled: true
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always

keystore:
    password: team92pass

feign:
    circuitbreaker:
        enabled: true

#Resilience4j Properties
resilience4j:
    circuitbreaker:
        instances:
            organization:
                register-health-indicator: true
                event-consumer-buffer-size: 10
                sliding-window-type: count_based
                sliding-window-size: 5
                failure-rate-threshold: 50
                wait-duration-in-open-state: 5
                permitted-number-of-calls-in-half-open-state: 3
                automatic-transition-from-open-to-half-open-enabled: true
    timelimiter:
        instances:
            organization:
                timeout-duration:
                    3s
    retry:
        instances:
            organization:
                max-attempts: 2
                wait-duration: 3s

app:
    feign:
        config:
            organization-client:
                name: organization-service
                url: http://${ORGANIZATION_HOST:localhost}:8186
            member-client:
                name: member-service
                url: http://${MEMBER_HOST:localhost}:8185

logstash:
    host: ${LOGSTASH_HOST_PORT:146.190.105.184:5000}

# Config Swagger  UI
springdoc:
    api-docs:
        path: /v1/api-docs
    swagger-ui:
        path: /swagger-ui-custom.html
        operationsSorter: method
        csrf:
            enabled: true