global:
    scrape_interval:     10s
    evaluation_interval: 10s

scrape_configs:
    - job_name: 'microservice_kong'
      static_configs:
          - targets: ['139.59.96.208:8001']
            labels:
                application: 'Microservice Project-Management Application'
