#_format_version: "1.1"
#services:
#    - name: organization-service
#      url: http://organization-service:8186
#      plugins: []
#      routes:
#          - name: organization-service-path-get
#            methods:
#                - GET
#            paths:
#                - /api/test
#            strip_path: false