
server:
    port: 8186

logging:
    level:
        ROOT: INFO
        com.dut.team92: DEBUG

spring:
    profiles:
        active: dev
    application:
        name: organization-service
        


